(function($){Drupal.behaviors.mydisplay={attach:function(context,settings){let base=Drupal.settings.covid_form.base_url+'/';$(".form-item-field-laboratory7-und select",context).once().change(function(){let id=$(this).val()
if(id){$.ajax({url:base+"dspl/lab/"+id,success:function(response){let arrival_date=$("#edit-field-arrival-date2 input").val();let vaccination_status=$("#edit-field-vaccination-status-und").val();let d=Date.parse(arrival_date);let date7=new Date(d)
date7.setDate(date7.getDate()+6);let date2=new Date(d)
date2.setDate(date2.getDate()+1);var content=`<p><strong>Lab Address: </strong> ${response.address}</p><p><strong> Contact Number: </strong> ${response.phone}</p>`
if(vaccination_status==3){content+=`<p><strong> Appointment Date (Day 2): </strong>${date2}</p>`;}else{content+=`<p><strong> Appointment Date (Day 2): </strong>${date2}</p><p><strong> Appointment Date (Day 7): </strong>${date7}</p>`;}
$("#lab-detail").html("<div class='lab-info well'>"+content+"</div>")}})}else{$("#lab-detail").html()}});$("#edit-field-preferred-currency input",context).once().on('change',function(){let currency=$(this).val()
let tids=[]
let names=[]
$(".form-item-field-laboratory7-und select option").each(function(){let val=$(this).val()
if(val!=='_none'){tids.push(val)}})
var vacinated=$(".form-item-field-vaccination-status-und select").val();$.ajax({url:`${base}dspl/currency/${currency}`,method:'POST',data:{tids:tids,vacinated:vacinated},success:function(response){$(".form-item-field-laboratory7-und select option").each(function(index,element){let val=$(this).val()
if(val!=='_none'){let name=$(this).text()
let name_arr=name.split("|");$(this).text(`${name_arr[0]} | ${response.amounts[index]}`)
$(".form-item-field-laboratory7-und select").trigger("chosen:updated");}})}})});$("#edit-field-state-in-nigeria select").once().change(function(){$("#edit-field-preferred-currency input").removeAttr("checked");})
$("#edit-field-country-of-first-departur2 select",context).once().on('change',function(event){let id=$(this).val()
let bits=Drupal.settings.nitpjs.bit_keys;if(bits.includes(id)){$("#myModal").modal('show');$("#edit-field-hotel-isolation-center-und--2").prop('required',true);$("#edit-field-hotel-isolation-center-und--2").attr('aria-required',true);let vvv=$("#edit-field-hotel-isolation-center-und--2").val()
if(vvv=="_none"){$("#edit-field-hotel-isolation-center-und--2").addClass('error');$("#edit-field-hotel-isolation-center-und--2").removeClass('valid');}}});$("#edit-field-mode-of-payment select",context).once().on('change',function(event){if($(this).val()==1){$("#modeofpaymentmodal").modal('show');}});$("#edit-field-state-ng select",context).once().on("change",function(){var val=$(this).val()
if(val=="14062"){$("#edit-field-mode-of-payment select").val("2")
$("#edit-field-mode-of-payment select option:contains('Bank Transfer')").attr("disabled",true)}else{$("#edit-field-mode-of-payment select option:contains('Bank Transfer')").removeAttr("disabled")}})
$("#edit-field-mode-of-payment select").on("change",function(){if($(this).val()==1){$("#edit-field-preferred-currency select").val("1")
var naira=$("#edit-field-preferred-currency select option:contains('Naira (₦)')")
$("#edit-field-preferred-currency select option").not(naira).each(function(){$(this).attr("disabled",true);})}else{$("#edit-field-preferred-currency select option").removeAttr("disabled");}})
$("#edit-field-confirm-passport-number-und-0-value",context).once().on('keyup change',function(event){if($(this).val()!=$("#edit-field-passport-number-und-0-value").val()){$(this).attr('aria-invalid',true);$(".field-name-field-confirm-passport-number .mydescription").html("<span class='text-danger error'>Passport number field not equal</span>")}else{$(".field-name-field-confirm-passport-number .mydescription").html("")}});$("#edit-field-email2-und-0-email",context).once().on('keyup change',function(event){if($(this).val()!=$("#edit-field-email-und-0-email").val()){$(this).attr('aria-invalid',true);$(".form-item-field-email2-und-0-email .mydescription").html("<span class='text-danger error'>Email field not equal</span>")}else{$(".form-item-field-email2-und-0-email .mydescription").html("")}});let accordion=$('div.field-group-accordion-wrapper');$(".mygroup-prev",context).once().on('click',function(){let pregroup=$(this).data('nextid');accordion.accordion("option","active",pregroup);});$(".mygroup-next",context).once().on('click',function(){let nextgroup=$(this).data('nextid');let current=nextgroup-1;let id=`#ui-accordion-1-panel-${current} select`;let allfilled=[];$(id).filter('.required').each(function(){let val=$(this).val();if(val==='_none'){allfilled.push(false);}})
let good;if(allfilled.length===0){good=true}else{good=allfilled.every(e=>e===true);}
if($('.field-group-accordion-wrapper select, .field-group-accordion-wrapper input, .field-group-accordion-wrapper textarea',this.wrapper).valid()){if(nextgroup-1===0){let email=$("#edit-field-email-und-0-email").val();let confirmemail=$("#edit-field-email2-und-0-email").val();let passport=$("#edit-field-passport-number-und-0-value").val();let confirmpassport=$("#edit-field-confirm-passport-number-und-0-value").val();let cp=(confirmpassport)?confirmpassport:passport;console.log(good)
if(email===confirmemail&&passport===cp&&good){accordion.accordion("option","active",nextgroup);}else{if(email!=confirmemail){$(".form-item-field-email2-und-0-email .mydescription").html("<span class='text-danger error'>Email field not equal</span>");}
if(passport!=confirmpassport){$(".field-name-field-confirm-passport-number .mydescription").html("<span class='text-danger error'>Passport number field not equal</span>");}}}else{if(good){accordion.accordion("option","active",nextgroup);}}}});$(".mygroup-submit",context).once().on('click',function(){$([document.documentElement,document.body]).animate({scrollTop:$("#edit-preview").offset().top},2000);});}}}(jQuery));